/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (database and object storage) */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CheckStatus
         * @enum {string}
         */
        CheckStatus: "ok" | "fail";
        /** DependencyCheck */
        DependencyCheck: {
            /**
             * Latency Ms
             * @description Time the check took, in milliseconds
             */
            latency_ms: number;
            status: components["schemas"]["CheckStatus"];
        };
        /**
         * Liveness
         * @example {
         *       "status": "ok"
         *     }
         */
        Liveness: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * Readiness
         * @example {
         *       "checks": {
         *         "database": {
         *           "latency_ms": 2.1,
         *           "status": "ok"
         *         },
         *         "object_storage": {
         *           "latency_ms": 8.4,
         *           "status": "ok"
         *         }
         *       },
         *       "environment": "development",
         *       "scanner": "stub",
         *       "status": "ok"
         *     }
         */
        Readiness: {
            /** Checks */
            checks: {
                [key: string]: components["schemas"]["DependencyCheck"];
            };
            /** Environment */
            environment: string;
            /**
             * Scanner
             * @description Active virus scanner: `stub` (dev only) or `clamav`
             */
            scanner: string;
            status: components["schemas"]["CheckStatus"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
}
